### ISSUE TITLE
Move the acronym search to a new window to improve usability and reduce popping

### ISSUE THREAD

**Issue by Racer159** [project-abydos/dakara#3]
Currently, the acronym search pops up large amounts of text as the user types, causing issues seeing the bullet history.  This should probably be a separate window or pane to provide this search.

**Comment by jeff-mccoy** [comment]
An easier first step might be to just limit the results or wait for two
characters to show a suggestion.

**Comment by Racer159** [comment]
I still think it is throwing a lot at the user at once since we have both synonyms and acronyms both above and below the text box.  It kinda makes it confusing as to what is happening (even if we did limit it to two chars).  They could be typing their bullet, and just would have random stuff appear above their input box.
